os.loadAPI("ComputerCraftMiningPog/apis/mine.lua")
print("ore ahead: " .. tostring(mine.oreAhead()))
print("ore up: " .. tostring(mine.oreUp()))
print("ore down: " .. tostring(mine.oreDown()))
mine.digOres()